### ISSUE TITLE
(understanding or bug) coctl put changes not reflected immediately in oco config-state.yaml

### ISSUE THREAD

**Issue by derezed88** [kumulustech/coctl#1]
When running coctl put -f <file>, I am not seeing changes reflected in oco's config-state.yaml.

When are changes reflected?  Do I need to do a restart post put?

I did a put for some simple saturation settings:
```(coctl) markjimenez@Marks-MacBook-Pro coctl % coctl put -f coconfig-saturation1.yaml 
Push coconfig-saturation1.yaml as a patch to the API
{"adjustment": {"control": {"userdata": {}}}, "measurement": {"control": {"load": {}, "userdata": {}, "delay": 60, "warmup": 0, "duration": 150}}, "optimization": {"mode": "saturation"}}
{'status': 'ok', 'config_changed': True, 'will_reset': True}
```

I have an ssh shell oco side.  I did a cat of config-state.yaml and it still had the old configuration (i.e. not matching coconfig-saturation1.yaml (above) data.

```root@ip-172-31-56-47:~/dev.opsani.com/mark-jimenez/oco# cat config-state.yaml
adjustment:
  control:
    userdata: {}
event_actions:
  action_failed:
    actions:
    - message: 'Optune (${event[''account_id'']}/${event[''app_id'']}): error running
        action for ${event[''account_id'']}/${event[''app_id'']} failed. Error: ${event[''message'']}'
...
```

**Comment by derezed88** [comment]
I also did a `coctl restart` after coctl put and a subsequent cat of oco config-state.yaml still had old config data.

**Comment by derezed88** [comment]
Related: Any changes to config-state.yaml are not reflected on `coctl restart`. An oco-side docker-compose down/up loop is needed for config-state.yaml changes to take affect and be reflected on a subsequent `coctl get`.

**Comment by derezed88** [comment]
Tried to replicate for a simple config change in front of Robert and it worked.  So when I next transition from saturation to canary configs again I will keep an eye on the behavior.

**Comment by rstarmer** [comment]
Closing for now.  New issues should be on https://github.com/opsani/coctl rather than here.
